<?php
/**
 * Theme Fonts Library
 *
 * @package Perennial
 */

/**
 * 350 Popular Google Fonts
 * @link https://fonts.google.com/
 *
 * @return array
 */
function perennial_fonts_library() {

	$fonts_library = array (
		'abeezee'                      => array( 'name' => 'ABeeZee',                     'category' => 'sans-serif' ),
		'abel'                         => array( 'name' => 'Abel',                        'category' => 'sans-serif' ),
		'abril-fatface'                => array( 'name' => 'Abril Fatface',               'category' => 'display' ),
		'aclonica'                     => array( 'name' => 'Aclonica',                    'category' => 'sans-serif' ),
		'acme'                         => array( 'name' => 'Acme',                        'category' => 'sans-serif' ),
		'actor'                        => array( 'name' => 'Actor',                       'category' => 'sans-serif' ),
		'adamina'                      => array( 'name' => 'Adamina',                     'category' => 'serif' ),
		'advent-pro'                   => array( 'name' => 'Advent Pro',                  'category' => 'sans-serif' ),
		'aldrich'                      => array( 'name' => 'Aldrich',                     'category' => 'sans-serif' ),
		'alef'                         => array( 'name' => 'Alef',                        'category' => 'sans-serif' ),
		'alegreya'                     => array( 'name' => 'Alegreya',                    'category' => 'serif' ),
		'alegreya-sans'                => array( 'name' => 'Alegreya Sans',               'category' => 'sans-serif' ),
		'alegreya-sans-sc'             => array( 'name' => 'Alegreya Sans SC',            'category' => 'sans-serif' ),
		'alegreya-sc'                  => array( 'name' => 'Alegreya SC',                 'category' => 'serif' ),
		'alex-brush'                   => array( 'name' => 'Alex Brush',                  'category' => 'handwriting' ),
		'alfa-slab-one'                => array( 'name' => 'Alfa Slab One',               'category' => 'display' ),
		'alice'                        => array( 'name' => 'Alice',                       'category' => 'serif' ),
		'alike'                        => array( 'name' => 'Alike',                       'category' => 'serif' ),
		'allan'                        => array( 'name' => 'Allan',                       'category' => 'display' ),
		'allerta'                      => array( 'name' => 'Allerta',                     'category' => 'sans-serif' ),
		'allerta-stencil'              => array( 'name' => 'Allerta Stencil',             'category' => 'sans-serif' ),
		'allura'                       => array( 'name' => 'Allura',                      'category' => 'handwriting' ),
		'amaranth'                     => array( 'name' => 'Amaranth',                    'category' => 'sans-serif' ),
		'amatic-sc'                    => array( 'name' => 'Amatic SC',                   'category' => 'handwriting' ),
		'amiri'                        => array( 'name' => 'Amiri',                       'category' => 'serif' ),
		'anaheim'                      => array( 'name' => 'Anaheim',                     'category' => 'sans-serif' ),
		'annie-use-your-telescope'     => array( 'name' => 'Annie Use Your Telescope',    'category' => 'handwriting' ),
		'anonymous-pro'                => array( 'name' => 'Anonymous Pro',               'category' => 'monospace' ),
		'antic'                        => array( 'name' => 'Antic',                       'category' => 'sans-serif' ),
		'antic-slab'                   => array( 'name' => 'Antic Slab',                  'category' => 'serif' ),
		'anton'                        => array( 'name' => 'Anton',                       'category' => 'sans-serif' ),
		'arapey'                       => array( 'name' => 'Arapey',                      'category' => 'serif' ),
		'arbutus-slab'                 => array( 'name' => 'Arbutus Slab',                'category' => 'serif' ),
		'architects-daughter'          => array( 'name' => 'Architects Daughter',         'category' => 'handwriting' ),
		'archivo-black'                => array( 'name' => 'Archivo Black',               'category' => 'sans-serif' ),
		'archivo-narrow'               => array( 'name' => 'Archivo Narrow',              'category' => 'sans-serif' ),
		'arimo'                        => array( 'name' => 'Arimo',                       'category' => 'sans-serif' ),
		'armata'                       => array( 'name' => 'Armata',                      'category' => 'sans-serif' ),
		'arvo'                         => array( 'name' => 'Arvo',                        'category' => 'serif' ),
		'asap'                         => array( 'name' => 'Asap',                        'category' => 'sans-serif' ),
		'audiowide'                    => array( 'name' => 'Audiowide',                   'category' => 'display' ),
		'average'                      => array( 'name' => 'Average',                     'category' => 'serif' ),
		'average-sans'                 => array( 'name' => 'Average Sans',                'category' => 'sans-serif' ),
		'bad-script'                   => array( 'name' => 'Bad Script',                  'category' => 'handwriting' ),
		'bangers'                      => array( 'name' => 'Bangers',                     'category' => 'display' ),
		'basic'                        => array( 'name' => 'Basic',                       'category' => 'sans-serif' ),
		'baumans'                      => array( 'name' => 'Baumans',                     'category' => 'display' ),
		'belleza'                      => array( 'name' => 'Belleza',                     'category' => 'sans-serif' ),
		'benchnine'                    => array( 'name' => 'BenchNine',                   'category' => 'sans-serif' ),
		'berkshire-swash'              => array( 'name' => 'Berkshire Swash',             'category' => 'handwriting' ),
		'bevan'                        => array( 'name' => 'Bevan',                       'category' => 'display' ),
		'bitter'                       => array( 'name' => 'Bitter',                      'category' => 'serif' ),
		'black-ops-one'                => array( 'name' => 'Black Ops One',               'category' => 'display' ),
		'boogaloo'                     => array( 'name' => 'Boogaloo',                    'category' => 'display' ),
		'bree-serif'                   => array( 'name' => 'Bree Serif',                  'category' => 'serif' ),
		'bubblegum-sans'               => array( 'name' => 'Bubblegum Sans',              'category' => 'display' ),
		'cabin'                        => array( 'name' => 'Cabin',                       'category' => 'sans-serif' ),
		'cabin-condensed'              => array( 'name' => 'Cabin Condensed',             'category' => 'sans-serif' ),
		'cabin-sketch'                 => array( 'name' => 'Cabin Sketch',                'category' => 'display' ),
		'cairo'                        => array( 'name' => 'Cairo',                       'category' => 'sans-serif' ),
		'calligraffitti'               => array( 'name' => 'Calligraffitti',              'category' => 'handwriting' ),
		'cambay'                       => array( 'name' => 'Cambay',                      'category' => 'sans-serif' ),
		'candal'                       => array( 'name' => 'Candal',                      'category' => 'sans-serif' ),
		'cantarell'                    => array( 'name' => 'Cantarell',                   'category' => 'sans-serif' ),
		'cantata-one'                  => array( 'name' => 'Cantata One',                 'category' => 'serif' ),
		'capriola'                     => array( 'name' => 'Capriola',                    'category' => 'sans-serif' ),
		'cardo'                        => array( 'name' => 'Cardo',                       'category' => 'serif' ),
		'carme'                        => array( 'name' => 'Carme',                       'category' => 'sans-serif' ),
		'carrois-gothic'               => array( 'name' => 'Carrois Gothic',              'category' => 'sans-serif' ),
		'carter-one'                   => array( 'name' => 'Carter One',                  'category' => 'display' ),
		'catamaran'                    => array( 'name' => 'Catamaran',                   'category' => 'sans-serif' ),
		'caudex'                       => array( 'name' => 'Caudex',                      'category' => 'serif' ),
		'ceviche-one'                  => array( 'name' => 'Ceviche One',                 'category' => 'display' ),
		'changa-one'                   => array( 'name' => 'Changa One',                  'category' => 'display' ),
		'chelsea-market'               => array( 'name' => 'Chelsea Market',              'category' => 'display' ),
		'cherry-cream-soda'            => array( 'name' => 'Cherry Cream Soda',           'category' => 'display' ),
		'chewy'                        => array( 'name' => 'Chewy',                       'category' => 'display' ),
		'chivo'                        => array( 'name' => 'Chivo',                       'category' => 'sans-serif' ),
		'cinzel'                       => array( 'name' => 'Cinzel',                      'category' => 'serif' ),
		'cinzel-decorative'            => array( 'name' => 'Cinzel Decorative',           'category' => 'display' ),
		'clicker-script'               => array( 'name' => 'Clicker Script',              'category' => 'handwriting' ),
		'coda'                         => array( 'name' => 'Coda',                        'category' => 'display' ),
		'comfortaa'                    => array( 'name' => 'Comfortaa',                   'category' => 'display' ),
		'coming-soon'                  => array( 'name' => 'Coming Soon',                 'category' => 'handwriting' ),
		'contrail-one'                 => array( 'name' => 'Contrail One',                'category' => 'display' ),
		'convergence'                  => array( 'name' => 'Convergence',                 'category' => 'sans-serif' ),
		'cookie'                       => array( 'name' => 'Cookie',                      'category' => 'handwriting' ),
		'copse'                        => array( 'name' => 'Copse',                       'category' => 'serif' ),
		'corben'                       => array( 'name' => 'Corben',                      'category' => 'display' ),
		'courgette'                    => array( 'name' => 'Courgette',                   'category' => 'handwriting' ),
		'cousine'                      => array( 'name' => 'Cousine',                     'category' => 'monospace' ),
		'coustard'                     => array( 'name' => 'Coustard',                    'category' => 'serif' ),
		'covered-by-your-grace'        => array( 'name' => 'Covered By Your Grace',       'category' => 'handwriting' ),
		'crafty-girls'                 => array( 'name' => 'Crafty Girls',                'category' => 'handwriting' ),
		'crete-round'                  => array( 'name' => 'Crete Round',                 'category' => 'serif' ),
		'crimson-text'                 => array( 'name' => 'Crimson Text',                'category' => 'serif' ),
		'cuprum'                       => array( 'name' => 'Cuprum',                      'category' => 'sans-serif' ),
		'cutive'                       => array( 'name' => 'Cutive',                      'category' => 'serif' ),
		'cutive-mono'                  => array( 'name' => 'Cutive Mono',                 'category' => 'monospace' ),
		'damion'                       => array( 'name' => 'Damion',                      'category' => 'handwriting' ),
		'dancing-script'               => array( 'name' => 'Dancing Script',              'category' => 'handwriting' ),
		'days-one'                     => array( 'name' => 'Days One',                    'category' => 'sans-serif' ),
		'denk-one'                     => array( 'name' => 'Denk One',                    'category' => 'sans-serif' ),
		'didact-gothic'                => array( 'name' => 'Didact Gothic',               'category' => 'sans-serif' ),
		'domine'                       => array( 'name' => 'Domine',                      'category' => 'serif' ),
		'doppio-one'                   => array( 'name' => 'Doppio One',                  'category' => 'sans-serif' ),
		'dosis'                        => array( 'name' => 'Dosis',                       'category' => 'sans-serif' ),
		'droid-sans'                   => array( 'name' => 'Droid Sans',                  'category' => 'sans-serif' ),
		'droid-sans-mono'              => array( 'name' => 'Droid Sans Mono',             'category' => 'monospace' ),
		'droid-serif'                  => array( 'name' => 'Droid Serif',                 'category' => 'serif' ),
		'duru-sans'                    => array( 'name' => 'Duru Sans',                   'category' => 'sans-serif' ),
		'eb-garamond'                  => array( 'name' => 'EB Garamond',                 'category' => 'serif' ),
		'economica'                    => array( 'name' => 'Economica',                   'category' => 'sans-serif' ),
		'ek-mukta'                     => array( 'name' => 'Ek Mukta',                    'category' => 'sans-serif' ),
		'electrolize'                  => array( 'name' => 'Electrolize',                 'category' => 'sans-serif' ),
		'enriqueta'                    => array( 'name' => 'Enriqueta',                   'category' => 'serif' ),
		'exo'                          => array( 'name' => 'Exo',                         'category' => 'sans-serif' ),
		'exo-2'                        => array( 'name' => 'Exo 2',                       'category' => 'sans-serif' ),
		'fanwood-text'                 => array( 'name' => 'Fanwood Text',                'category' => 'serif' ),
		'fauna-one'                    => array( 'name' => 'Fauna One',                   'category' => 'serif' ),
		'fira-mono'                    => array( 'name' => 'Fira Mono',                   'category' => 'monospace' ),
		'fira-sans'                    => array( 'name' => 'Fira Sans',                   'category' => 'sans-serif' ),
		'fjalla-one'                   => array( 'name' => 'Fjalla One',                  'category' => 'sans-serif' ),
		'fontdiner-swanky'             => array( 'name' => 'Fontdiner Swanky',            'category' => 'display' ),
		'forum'                        => array( 'name' => 'Forum',                       'category' => 'display' ),
		'francois-one'                 => array( 'name' => 'Francois One',                'category' => 'sans-serif' ),
		'freckle-face'                 => array( 'name' => 'Freckle Face',                'category' => 'display' ),
		'fredericka-the-great'         => array( 'name' => 'Fredericka the Great',        'category' => 'display' ),
		'fredoka-one'                  => array( 'name' => 'Fredoka One',                 'category' => 'display' ),
		'frijole'                      => array( 'name' => 'Frijole',                     'category' => 'display' ),
		'fugaz-one'                    => array( 'name' => 'Fugaz One',                   'category' => 'display' ),
		'gentium-basic'                => array( 'name' => 'Gentium Basic',               'category' => 'serif' ),
		'gentium-book-basic'           => array( 'name' => 'Gentium Book Basic',          'category' => 'serif' ),
		'gilda-display'                => array( 'name' => 'Gilda Display',               'category' => 'serif' ),
		'glegoo'                       => array( 'name' => 'Glegoo',                      'category' => 'serif' ),
		'gloria-hallelujah'            => array( 'name' => 'Gloria Hallelujah',           'category' => 'handwriting' ),
		'gochi-hand'                   => array( 'name' => 'Gochi Hand',                  'category' => 'handwriting' ),
		'goudy-bookletter-1911'        => array( 'name' => 'Goudy Bookletter 1911',       'category' => 'serif' ),
		'graduate'                     => array( 'name' => 'Graduate',                    'category' => 'display' ),
		'grand-hotel'                  => array( 'name' => 'Grand Hotel',                 'category' => 'handwriting' ),
		'great-vibes'                  => array( 'name' => 'Great Vibes',                 'category' => 'handwriting' ),
		'gruppo'                       => array( 'name' => 'Gruppo',                      'category' => 'display' ),
		'gudea'                        => array( 'name' => 'Gudea',                       'category' => 'sans-serif' ),
		'halant'                       => array( 'name' => 'Halant',                      'category' => 'serif' ),
		'hammersmith-one'              => array( 'name' => 'Hammersmith One',             'category' => 'sans-serif' ),
		'handlee'                      => array( 'name' => 'Handlee',                     'category' => 'handwriting' ),
		'hanuman'                      => array( 'name' => 'Hanuman',                     'category' => 'serif' ),
		'hind'                         => array( 'name' => 'Hind',                        'category' => 'sans-serif' ),
		'hind-siliguri'                => array( 'name' => 'Hind Siliguri',               'category' => 'sans-serif' ),
		'hind-vadodara'                => array( 'name' => 'Hind Vadodara',               'category' => 'sans-serif' ),
		'homemade-apple'               => array( 'name' => 'Homemade Apple',              'category' => 'handwriting' ),
		'homenaje'                     => array( 'name' => 'Homenaje',                    'category' => 'sans-serif' ),
		'inconsolata'                  => array( 'name' => 'Inconsolata',                 'category' => 'monospace' ),
		'inder'                        => array( 'name' => 'Inder',                       'category' => 'sans-serif' ),
		'indie-flower'                 => array( 'name' => 'Indie Flower',                'category' => 'handwriting' ),
		'istok-web'                    => array( 'name' => 'Istok Web',                   'category' => 'sans-serif' ),
		'italianno'                    => array( 'name' => 'Italianno',                   'category' => 'handwriting' ),
		'jockey-one'                   => array( 'name' => 'Jockey One',                  'category' => 'sans-serif' ),
		'josefin-sans'                 => array( 'name' => 'Josefin Sans',                'category' => 'sans-serif' ),
		'josefin-slab'                 => array( 'name' => 'Josefin Slab',                'category' => 'serif' ),
		'julius-sans-one'              => array( 'name' => 'Julius Sans One',             'category' => 'sans-serif' ),
		'jura'                         => array( 'name' => 'Jura',                        'category' => 'sans-serif' ),
		'just-another-hand'            => array( 'name' => 'Just Another Hand',           'category' => 'handwriting' ),
		'kalam'                        => array( 'name' => 'Kalam',                       'category' => 'handwriting' ),
		'kameron'                      => array( 'name' => 'Kameron',                     'category' => 'serif' ),
		'kanit'                        => array( 'name' => 'Kanit',                       'category' => 'sans-serif' ),
		'karla'                        => array( 'name' => 'Karla',                       'category' => 'sans-serif' ),
		'kaushan-script'               => array( 'name' => 'Kaushan Script',              'category' => 'handwriting' ),
		'khand'                        => array( 'name' => 'Khand',                       'category' => 'sans-serif' ),
		'khula'                        => array( 'name' => 'Khula',                       'category' => 'sans-serif' ),
		'kreon'                        => array( 'name' => 'Kreon',                       'category' => 'serif' ),
		'lakki-reddy'                  => array( 'name' => 'Lakki Reddy',                 'category' => 'handwriting' ),
		'lateef'                       => array( 'name' => 'Lateef',                      'category' => 'handwriting' ),
		'lato'                         => array( 'name' => 'Lato',                        'category' => 'sans-serif' ),
		'leckerli-one'                 => array( 'name' => 'Leckerli One',                'category' => 'handwriting' ),
		'lemon'                        => array( 'name' => 'Lemon',                       'category' => 'display' ),
		'libre-baskerville'            => array( 'name' => 'Libre Baskerville',           'category' => 'serif' ),
		'lilita-one'                   => array( 'name' => 'Lilita One',                  'category' => 'display' ),
		'limelight'                    => array( 'name' => 'Limelight',                   'category' => 'display' ),
		'lobster'                      => array( 'name' => 'Lobster',                     'category' => 'display' ),
		'lobster-two'                  => array( 'name' => 'Lobster Two',                 'category' => 'display' ),
		'londrina-solid'               => array( 'name' => 'Londrina Solid',              'category' => 'display' ),
		'lora'                         => array( 'name' => 'Lora',                        'category' => 'serif' ),
		'luckiest-guy'                 => array( 'name' => 'Luckiest Guy',                'category' => 'display' ),
		'lusitana'                     => array( 'name' => 'Lusitana',                    'category' => 'serif' ),
		'lustria'                      => array( 'name' => 'Lustria',                     'category' => 'serif' ),
		'magra'                        => array( 'name' => 'Magra',                       'category' => 'sans-serif' ),
		'mako'                         => array( 'name' => 'Mako',                        'category' => 'sans-serif' ),
		'marcellus'                    => array( 'name' => 'Marcellus',                   'category' => 'serif' ),
		'marcellus-sc'                 => array( 'name' => 'Marcellus SC',                'category' => 'serif' ),
		'marck-script'                 => array( 'name' => 'Marck Script',                'category' => 'handwriting' ),
		'marmelad'                     => array( 'name' => 'Marmelad',                    'category' => 'sans-serif' ),
		'martel'                       => array( 'name' => 'Martel',                      'category' => 'serif' ),
		'marvel'                       => array( 'name' => 'Marvel',                      'category' => 'sans-serif' ),
		'mate'                         => array( 'name' => 'Mate',                        'category' => 'serif' ),
		'maven-pro'                    => array( 'name' => 'Maven Pro',                   'category' => 'sans-serif' ),
		'merienda'                     => array( 'name' => 'Merienda',                    'category' => 'handwriting' ),
		'merienda-one'                 => array( 'name' => 'Merienda One',                'category' => 'handwriting' ),
		'merriweather'                 => array( 'name' => 'Merriweather',                'category' => 'serif' ),
		'merriweather-sans'            => array( 'name' => 'Merriweather Sans',           'category' => 'sans-serif' ),
		'metrophobic'                  => array( 'name' => 'Metrophobic',                 'category' => 'sans-serif' ),
		'michroma'                     => array( 'name' => 'Michroma',                    'category' => 'sans-serif' ),
		'molengo'                      => array( 'name' => 'Molengo',                     'category' => 'sans-serif' ),
		'monda'                        => array( 'name' => 'Monda',                       'category' => 'sans-serif' ),
		'monoton'                      => array( 'name' => 'Monoton',                     'category' => 'display' ),
		'montez'                       => array( 'name' => 'Montez',                      'category' => 'handwriting' ),
		'montserrat'                   => array( 'name' => 'Montserrat',                  'category' => 'sans-serif' ),
		'montserrat-alternates'        => array( 'name' => 'Montserrat Alternates',       'category' => 'sans-serif' ),
		'mouse-memoirs'                => array( 'name' => 'Mouse Memoirs',               'category' => 'sans-serif' ),
		'mr-dafoe'                     => array( 'name' => 'Mr Dafoe',                    'category' => 'handwriting' ),
		'muli'                         => array( 'name' => 'Muli',                        'category' => 'sans-serif' ),
		'neucha'                       => array( 'name' => 'Neucha',                      'category' => 'handwriting' ),
		'neuton'                       => array( 'name' => 'Neuton',                      'category' => 'serif' ),
		'news-cycle'                   => array( 'name' => 'News Cycle',                  'category' => 'sans-serif' ),
		'niconne'                      => array( 'name' => 'Niconne',                     'category' => 'handwriting' ),
		'nixie-one'                    => array( 'name' => 'Nixie One',                   'category' => 'display' ),
		'nobile'                       => array( 'name' => 'Nobile',                      'category' => 'sans-serif' ),
		'nothing-you-could-do'         => array( 'name' => 'Nothing You Could Do',        'category' => 'handwriting' ),
		'noticia-text'                 => array( 'name' => 'Noticia Text',                'category' => 'serif' ),
		'noto-sans'                    => array( 'name' => 'Noto Sans',                   'category' => 'sans-serif' ),
		'noto-serif'                   => array( 'name' => 'Noto Serif',                  'category' => 'serif' ),
		'nunito'                       => array( 'name' => 'Nunito',                      'category' => 'sans-serif' ),
		'old-standard-tt'              => array( 'name' => 'Old Standard TT',             'category' => 'serif' ),
		'oleo-script'                  => array( 'name' => 'Oleo Script',                 'category' => 'display' ),
		'oleo-script-swash-caps'       => array( 'name' => 'Oleo Script Swash Caps',      'category' => 'display' ),
		'open-sans'                    => array( 'name' => 'Open Sans',                   'category' => 'sans-serif' ),
		'open-sans-condensed'          => array( 'name' => 'Open Sans Condensed',         'category' => 'sans-serif' ),
		'oranienbaum'                  => array( 'name' => 'Oranienbaum',                 'category' => 'serif' ),
		'orbitron'                     => array( 'name' => 'Orbitron',                    'category' => 'sans-serif' ),
		'oswald'                       => array( 'name' => 'Oswald',                      'category' => 'sans-serif' ),
		'overlock'                     => array( 'name' => 'Overlock',                    'category' => 'display' ),
		'ovo'                          => array( 'name' => 'Ovo',                         'category' => 'serif' ),
		'oxygen'                       => array( 'name' => 'Oxygen',                      'category' => 'sans-serif' ),
		'oxygen-mono'                  => array( 'name' => 'Oxygen Mono',                 'category' => 'monospace' ),
		'pacifico'                     => array( 'name' => 'Pacifico',                    'category' => 'handwriting' ),
		'parisienne'                   => array( 'name' => 'Parisienne',                  'category' => 'handwriting' ),
		'passion-one'                  => array( 'name' => 'Passion One',                 'category' => 'display' ),
		'pathway-gothic-one'           => array( 'name' => 'Pathway Gothic One',          'category' => 'sans-serif' ),
		'patrick-hand'                 => array( 'name' => 'Patrick Hand',                'category' => 'handwriting' ),
		'patua-one'                    => array( 'name' => 'Patua One',                   'category' => 'display' ),
		'paytone-one'                  => array( 'name' => 'Paytone One',                 'category' => 'sans-serif' ),
		'permanent-marker'             => array( 'name' => 'Permanent Marker',            'category' => 'handwriting' ),
		'petit-formal-script'          => array( 'name' => 'Petit Formal Script',         'category' => 'handwriting' ),
		'philosopher'                  => array( 'name' => 'Philosopher',                 'category' => 'sans-serif' ),
		'pinyon-script'                => array( 'name' => 'Pinyon Script',               'category' => 'handwriting' ),
		'play'                         => array( 'name' => 'Play',                        'category' => 'sans-serif' ),
		'playball'                     => array( 'name' => 'Playball',                    'category' => 'display' ),
		'playfair-display'             => array( 'name' => 'Playfair Display',            'category' => 'serif' ),
		'playfair-display-sc'          => array( 'name' => 'Playfair Display SC',         'category' => 'serif' ),
		'poiret-one'                   => array( 'name' => 'Poiret One',                  'category' => 'display' ),
		'pompiere'                     => array( 'name' => 'Pompiere',                    'category' => 'display' ),
		'pontano-sans'                 => array( 'name' => 'Pontano Sans',                'category' => 'sans-serif' ),
		'poppins'                      => array( 'name' => 'Poppins',                     'category' => 'sans-serif' ),
		'port-lligat-slab'             => array( 'name' => 'Port Lligat Slab',            'category' => 'serif' ),
		'pragati-narrow'               => array( 'name' => 'Pragati Narrow',              'category' => 'sans-serif' ),
		'prata'                        => array( 'name' => 'Prata',                       'category' => 'serif' ),
		'press-start-2p'               => array( 'name' => 'Press Start 2P',              'category' => 'display' ),
		'pt-mono'                      => array( 'name' => 'PT Mono',                     'category' => 'monospace' ),
		'pt-sans'                      => array( 'name' => 'PT Sans',                     'category' => 'sans-serif' ),
		'pt-sans-caption'              => array( 'name' => 'PT Sans Caption',             'category' => 'sans-serif' ),
		'pt-sans-narrow'               => array( 'name' => 'PT Sans Narrow',              'category' => 'sans-serif' ),
		'pt-serif'                     => array( 'name' => 'PT Serif',                    'category' => 'serif' ),
		'pt-serif-caption'             => array( 'name' => 'PT Serif Caption',            'category' => 'serif' ),
		'puritan'                      => array( 'name' => 'Puritan',                     'category' => 'sans-serif' ),
		'quantico'                     => array( 'name' => 'Quantico',                    'category' => 'sans-serif' ),
		'quattrocento'                 => array( 'name' => 'Quattrocento',                'category' => 'serif' ),
		'quattrocento-sans'            => array( 'name' => 'Quattrocento Sans',           'category' => 'sans-serif' ),
		'questrial'                    => array( 'name' => 'Questrial',                   'category' => 'sans-serif' ),
		'quicksand'                    => array( 'name' => 'Quicksand',                   'category' => 'sans-serif' ),
		'quintessential'               => array( 'name' => 'Quintessential',              'category' => 'handwriting' ),
		'racing-sans-one'              => array( 'name' => 'Racing Sans One',             'category' => 'display' ),
		'radley'                       => array( 'name' => 'Radley',                      'category' => 'serif' ),
		'rajdhani'                     => array( 'name' => 'Rajdhani',                    'category' => 'sans-serif' ),
		'raleway'                      => array( 'name' => 'Raleway',                     'category' => 'sans-serif' ),
		'rambla'                       => array( 'name' => 'Rambla',                      'category' => 'sans-serif' ),
		'rancho'                       => array( 'name' => 'Rancho',                      'category' => 'handwriting' ),
		'reenie-beanie'                => array( 'name' => 'Reenie Beanie',               'category' => 'handwriting' ),
		'righteous'                    => array( 'name' => 'Righteous',                   'category' => 'display' ),
		'roboto'                       => array( 'name' => 'Roboto',                      'category' => 'sans-serif' ),
		'roboto-condensed'             => array( 'name' => 'Roboto Condensed',            'category' => 'sans-serif' ),
		'roboto-mono'                  => array( 'name' => 'Roboto Mono',                 'category' => 'monospace' ),
		'roboto-slab'                  => array( 'name' => 'Roboto Slab',                 'category' => 'serif' ),
		'rochester'                    => array( 'name' => 'Rochester',                   'category' => 'handwriting' ),
		'rock-salt'                    => array( 'name' => 'Rock Salt',                   'category' => 'handwriting' ),
		'rokkitt'                      => array( 'name' => 'Rokkitt',                     'category' => 'serif' ),
		'ropa-sans'                    => array( 'name' => 'Ropa Sans',                   'category' => 'sans-serif' ),
		'rosario'                      => array( 'name' => 'Rosario',                     'category' => 'sans-serif' ),
		'rubik'                        => array( 'name' => 'Rubik',                       'category' => 'sans-serif' ),
		'ruda'                         => array( 'name' => 'Ruda',                        'category' => 'sans-serif' ),
		'russo-one'                    => array( 'name' => 'Russo One',                   'category' => 'sans-serif' ),
		'sacramento'                   => array( 'name' => 'Sacramento',                  'category' => 'handwriting' ),
		'sanchez'                      => array( 'name' => 'Sanchez',                     'category' => 'serif' ),
		'sansita-one'                  => array( 'name' => 'Sansita One',                 'category' => 'display' ),
		'sarala'                       => array( 'name' => 'Sarala',                      'category' => 'sans-serif' ),
		'satisfy'                      => array( 'name' => 'Satisfy',                     'category' => 'handwriting' ),
		'scada'                        => array( 'name' => 'Scada',                       'category' => 'sans-serif' ),
		'schoolbell'                   => array( 'name' => 'Schoolbell',                  'category' => 'handwriting' ),
		'shadows-into-light'           => array( 'name' => 'Shadows Into Light',          'category' => 'handwriting' ),
		'shadows-into-light-two'       => array( 'name' => 'Shadows Into Light Two',      'category' => 'handwriting' ),
		'share'                        => array( 'name' => 'Share',                       'category' => 'display' ),
		'short-stack'                  => array( 'name' => 'Short Stack',                 'category' => 'handwriting' ),
		'sigmar-one'                   => array( 'name' => 'Sigmar One',                  'category' => 'display' ),
		'signika'                      => array( 'name' => 'Signika',                     'category' => 'sans-serif' ),
		'signika-negative'             => array( 'name' => 'Signika Negative',            'category' => 'sans-serif' ),
		'sintony'                      => array( 'name' => 'Sintony',                     'category' => 'sans-serif' ),
		'six-caps'                     => array( 'name' => 'Six Caps',                    'category' => 'sans-serif' ),
		'slabo-13px'                   => array( 'name' => 'Slabo 13px',                  'category' => 'serif' ),
		'slabo-27px'                   => array( 'name' => 'Slabo 27px',                  'category' => 'serif' ),
		'slackey'                      => array( 'name' => 'Slackey',                     'category' => 'display' ),
		'sorts-mill-goudy'             => array( 'name' => 'Sorts Mill Goudy',            'category' => 'serif' ),
		'source-code-pro'              => array( 'name' => 'Source Code Pro',             'category' => 'monospace' ),
		'source-sans-pro'              => array( 'name' => 'Source Sans Pro',             'category' => 'sans-serif' ),
		'source-serif-pro'             => array( 'name' => 'Source Serif Pro',            'category' => 'serif' ),
		'special-elite'                => array( 'name' => 'Special Elite',               'category' => 'display' ),
		'spinnaker'                    => array( 'name' => 'Spinnaker',                   'category' => 'sans-serif' ),
		'squada-one'                   => array( 'name' => 'Squada One',                  'category' => 'display' ),
		'sree-krushnadevaraya'         => array( 'name' => 'Sree Krushnadevaraya',        'category' => 'serif' ),
		'sue-ellen-francisco'          => array( 'name' => 'Sue Ellen Francisco',         'category' => 'handwriting' ),
		'syncopate'                    => array( 'name' => 'Syncopate',                   'category' => 'sans-serif' ),
		'tangerine'                    => array( 'name' => 'Tangerine',                   'category' => 'handwriting' ),
		'tauri'                        => array( 'name' => 'Tauri',                       'category' => 'sans-serif' ),
		'teko'                         => array( 'name' => 'Teko',                        'category' => 'sans-serif' ),
		'telex'                        => array( 'name' => 'Telex',                       'category' => 'sans-serif' ),
		'tenor-sans'                   => array( 'name' => 'Tenor Sans',                  'category' => 'sans-serif' ),
		'the-girl-next-door'           => array( 'name' => 'The Girl Next Door',          'category' => 'handwriting' ),
		'tinos'                        => array( 'name' => 'Tinos',                       'category' => 'serif' ),
		'titillium-web'                => array( 'name' => 'Titillium Web',               'category' => 'sans-serif' ),
		'trocchi'                      => array( 'name' => 'Trocchi',                     'category' => 'serif' ),
		'ubuntu'                       => array( 'name' => 'Ubuntu',                      'category' => 'sans-serif' ),
		'ubuntu-condensed'             => array( 'name' => 'Ubuntu Condensed',            'category' => 'sans-serif' ),
		'ubuntu-mono'                  => array( 'name' => 'Ubuntu Mono',                 'category' => 'monospace' ),
		'ultra'                        => array( 'name' => 'Ultra',                       'category' => 'serif' ),
		'unica-one'                    => array( 'name' => 'Unica One',                   'category' => 'display' ),
		'unkempt'                      => array( 'name' => 'Unkempt',                     'category' => 'display' ),
		'varela'                       => array( 'name' => 'Varela',                      'category' => 'sans-serif' ),
		'varela-round'                 => array( 'name' => 'Varela Round',                'category' => 'sans-serif' ),
		'vidaloka'                     => array( 'name' => 'Vidaloka',                    'category' => 'serif' ),
		'viga'                         => array( 'name' => 'Viga',                        'category' => 'sans-serif' ),
		'volkhov'                      => array( 'name' => 'Volkhov',                     'category' => 'serif' ),
		'vollkorn'                     => array( 'name' => 'Vollkorn',                    'category' => 'serif' ),
		'voltaire'                     => array( 'name' => 'Voltaire',                    'category' => 'sans-serif' ),
		'waiting-for-the-sunrise'      => array( 'name' => 'Waiting for the Sunrise',     'category' => 'handwriting' ),
		'walter-turncoat'              => array( 'name' => 'Walter Turncoat',             'category' => 'handwriting' ),
		'wire-one'                     => array( 'name' => 'Wire One',                    'category' => 'sans-serif' ),
		'work-sans'                    => array( 'name' => 'Work Sans',                   'category' => 'sans-serif' ),
		'yanone-kaffeesatz'            => array( 'name' => 'Yanone Kaffeesatz',           'category' => 'sans-serif' ),
		'yantramanav'                  => array( 'name' => 'Yantramanav',                 'category' => 'sans-serif' ),
		'yellowtail'                   => array( 'name' => 'Yellowtail',                  'category' => 'handwriting' ),
		'yesteryear'                   => array( 'name' => 'Yesteryear',                  'category' => 'handwriting' ),
		'zeyada'                       => array( 'name' => 'Zeyada',                      'category' => 'handwriting' ),
	);

	return apply_filters( 'perennial_fonts_library', $fonts_library );

}
